infoslack:
  image: "infoslack/dvwa"
  ports:
    - "80:80"
    - "3306:3306"
  environment:
    - MYSQL_PASS=p@ssw0rd

citizenstig:
  image: "citizenstig/nowasp"
  ports:
    - "8081:8081"

webgoat:
  image: "webgoat/webgoat-container"
  ports:
    - "8080:8082"
