infoslack:
  image: "infoslack/dvwa"
  ports:
    - "80:80"
  environment:
    - MYSQL_PASS=p@ssw0rd

citizenstig:
  image: "citizenstig/nowasp"
  ports:
    - "8081:80"
  environment:
    - MYSQL_PASS=p@ssw0rd

webgoat:
  image: "webgoat/webgoat-8.0"
  ports:
    - "8080:8080"

mysql:
  image: "mysql/mysql-server"
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd
