web:
  image: "infoslack/dvwa"
  ports:
    - "80:80"
  environment:
    - MYSQL_PASS=p@ssw0rd

citizenstig:
  image: "citizenstig/nowasp"
  ports:
    - "8081:80"
  environment:
    - MYSQL_PASS=p@ssw0rd

webgoat:
  image: "webgoat/webgoat-8.0"
  ports:
    - "8080:8080"

open-ninja:
  image: "opendns/security-ninjas"
  ports:
    - "8899:80"

wordpress:
  image: "wpscanteam/vulnerablewordpress"
  ports:
    - "8088:80"
    - "3305:3306"

basic-auth:
  image: "beevelop/nginx-basic-auth"
  ports:
    - "8087:80"
  links:
    - "web:web"

mysql:
  image: "mysql/mysql-server"
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd

selenium-standalone:
  image: "selenium/standalone-firefox-debug"
  ports:
    - "4444:4444"
